### ISSUE TITLE
Learning JAVA from .NET

### ISSUE THREAD

**Issue by raywmc** [SupportCamp/General-Tickets#3]
Urgently need information and ways to learn java from .net knowledge and experience...

**Comment by SupportCamp** [comment]
Learning Java Syntax from .NET perspective:
Java and C# Comparison
http://harding.edu/fmccown/java_csharp_comparison.html

Generate documentation from code (YouTube):
UML Plugin(CODE TO UML) NetBeans (7.0-8.0.1) - Classes to Diagrams
https://www.youtube.com/watch?v=MdnDhMH6g78
